### ISSUE TITLE
The interceptor registry is too rigid

### ISSUE THREAD

**Issue by jech** [pion/interceptor#11]
Instead of having an interceptor registry and binding it to the media engine, perhaps it would be enough to have a method that adds an interceptor to a given PC? This, in particular, would make it easy to share state between interceptors:
```
state := make([]stateful, 42);
i1 := &Interceptor1{state: state}
i2 := &Interceptor2{state: state}
AddInterceptor(pc, i1)
AddInterceptor(pc, i2)
```
Let me give another example.  Suppose you want to write an interceptor to generate sender/receiver reports (which is something we definitely want to see in Pion, since this functionality is essential both for lipsync and getting decent datarates).  The interceptor will need a data structure to keep information about time offsets and jitter statistics; this data structure is likely to be per-PC, and therefore a different instance will be used for each PC.  Thus, you'll most likely want to stick a separate interceptor on each PC, rather than sticking it in the MediaEngine.

**Comment by Sean-Der** [comment]
Sorry for the slow response to this @jech !

You can do this with the API object today. You construct an `API` object and can pass it an Registry (a list of Interceptors). Those interceptors can be anything you want (and have state passed to their constructors as you wish).

@at-wat described this pattern pretty well here https://github.com/pion/webrtc/issues/1749#issuecomment-817498252
