### ISSUE TITLE
Optimise `SendSideBWE.WriteRTCP`

### ISSUE THREAD

**Issue by adityaa30** [pion/interceptor#141]
## Summary

Right now the `SendSideBWE.WriteRTCP` calls `delayController.updateDelayEstimate` passing all list of acknowledgements in each `rtcp.TransportLayerCC` packet. Current implementation passes each acknowledgement one by one in `ackPipe` and `ackRatePipe` which can become bottleneck when the number of acknowledgements is >100 in a twcc feedback report which is possible for a large room with multiple active audio/video tracks.  

https://github.com/pion/interceptor/blob/0748586beeecf8c4bd66824ffde1b097d6bee431/pkg/gcc/delay_based_bwe.go#L94-L100

## Motivation

I have been trying to enable `transport-cc` for audio tracks in order to get transport wide metrics (loss, jitter, rtt) used to calculate call quality for audio-only rooms. After enabling for audio, I observed random spikes in cpu usage (usage as 10x compared to without `transport-cc` for audio) for certain calls [where most of peers were *android* clients using [native webrtc](https://webrtc.github.io/webrtc-org/native-code/android/)]. 

Such spikes happened intermittently and looking at below cpu usage via `pprof` about 50% of the cpu was busy processing twcc packets. 

<img width="586" alt="Screenshot 2022-06-14 at 02 10 51" src="https://user-images.githubusercontent.com/37837542/173441528-8a20e124-0e59-40b4-bd9a-8d9f685f055f.png">

The exact cause for this is unknown as it happens for 1 out of 10 calls. 

## Describe alternatives you've considered

In search of the reason behind cpu spikes I tried optimising the `delayController.updateDelayEstimate` method  by passing all acknowledgements at once and observed some improvement with below benchmarking results. 

Benchmark results for SendSideBWE [#142]

1.  Original Implementation: Send 1 ack at a time to each channel  
    
    ```
    ❯ go test -run=BenchmarkSendSideBWE -bench=BenchmarkSendSideBWE_WriteRTCP -v -benchtime 5s -count 3
    goos: darwin
    goarch: arm64
    pkg: github.com/pion/interceptor/pkg/gcc
    BenchmarkSendSideBWE_WriteRTCP
    BenchmarkSendSideBWE_WriteRTCP/num_sequences=10
    BenchmarkSendSideBWE_WriteRTCP/num_sequences=10-10                824898              7663 ns/op
    BenchmarkSendSideBWE_WriteRTCP/num_sequences=10-10                868285              7222 ns/op
    BenchmarkSendSideBWE_WriteRTCP/num_sequences=10-10                833091              7747 ns/op
    BenchmarkSendSideBWE_WriteRTCP/num_sequences=100
    BenchmarkSendSideBWE_WriteRTCP/num_sequences=100-10               113960             52894 ns/op
    BenchmarkSendSideBWE_WriteRTCP/num_sequences=100-10                97976             52030 ns/op
    BenchmarkSendSideBWE_WriteRTCP/num_sequences=100-10               115982             52788 ns/op
    BenchmarkSendSideBWE_WriteRTCP/num_sequences=500
    BenchmarkSendSideBWE_WriteRTCP/num_sequences=500-10                24283            257929 ns/op
    BenchmarkSendSideBWE_WriteRTCP/num_sequences=500-10                24034            248203 ns/op
    BenchmarkSendSideBWE_WriteRTCP/num_sequences=500-10                23204            246539 ns/op
    BenchmarkSendSideBWE_WriteRTCP/num_sequences=1000
    BenchmarkSendSideBWE_WriteRTCP/num_sequences=1000-10               10000            511518 ns/op
    BenchmarkSendSideBWE_WriteRTCP/num_sequences=1000-10               10000            512859 ns/op
    BenchmarkSendSideBWE_WriteRTCP/num_sequences=1000-10               10000            510880 ns/op
    PASS
    ok      github.com/pion/interceptor/pkg/gcc     79.384s
    
    ```
    
2.  Optimised: Send all acks in each `rtcp.TransportLayerCC` pkt at once  
    
    ```
    ❯ go test -run=BenchmarkSendSideBWE -bench=BenchmarkSendSideBWE_WriteRTCP -v -benchtime 5s -count 3
    goos: darwin
    goarch: arm64
    pkg: github.com/pion/interceptor/pkg/gcc
    BenchmarkSendSideBWE_WriteRTCP
    BenchmarkSendSideBWE_WriteRTCP/num_sequences=10
    BenchmarkSendSideBWE_WriteRTCP/num_sequences=10-10               1753162              3631 ns/op
    BenchmarkSendSideBWE_WriteRTCP/num_sequences=10-10               1494188              3587 ns/op
    BenchmarkSendSideBWE_WriteRTCP/num_sequences=10-10               1739785              3548 ns/op
    BenchmarkSendSideBWE_WriteRTCP/num_sequences=100
    BenchmarkSendSideBWE_WriteRTCP/num_sequences=100-10               399759             17435 ns/op
    BenchmarkSendSideBWE_WriteRTCP/num_sequences=100-10               383304             16141 ns/op
    BenchmarkSendSideBWE_WriteRTCP/num_sequences=100-10               399852             15329 ns/op
    BenchmarkSendSideBWE_WriteRTCP/num_sequences=500
    BenchmarkSendSideBWE_WriteRTCP/num_sequences=500-10               101514             58903 ns/op
    BenchmarkSendSideBWE_WriteRTCP/num_sequences=500-10                87471             59383 ns/op
    BenchmarkSendSideBWE_WriteRTCP/num_sequences=500-10               100100             62173 ns/op
    BenchmarkSendSideBWE_WriteRTCP/num_sequences=1000
    BenchmarkSendSideBWE_WriteRTCP/num_sequences=1000-10               53884            111935 ns/op
    BenchmarkSendSideBWE_WriteRTCP/num_sequences=1000-10               48418            123194 ns/op
    BenchmarkSendSideBWE_WriteRTCP/num_sequences=1000-10               47625            128780 ns/op
    PASS
    ok      github.com/pion/interceptor/pkg/gcc     90.325s
    ```
    

Comparison:
| Count delta chunks per rtcp pkt / Implementation | 1 at a time | All at once | Improvement |
|--|--|--|--|
| 10 to 15 | 7544 ns/op | 3588 ns/op | 2.1x |
| 100 to 150 | 52570 ns/op | 16301 ns/op| 3.2x |
| 500 to 750 | 250890 ns/op | 60153 ns/op | 4.1x |
| 1000 to 1500 | 511752 ns/op | 121303 ns/op | 4.2x |

**Comment by mengelbart** [comment]
Should be fixed with #147
