### ISSUE TITLE
GCC: aggressive estimated bitrate drop on seemingly healthy connection

### ISSUE THREAD

**Issue by streamer45** [pion/interceptor#156]
### Your environment.
  - Version:  a82b843
  - Browser: Firefox 103.0 can reproduce this issue with some consistency.

### What did you do?

I am having Firefox subscribe to a simulcasted video stream originally coming from Chrome through a pion SFU.

### What did you expect?

The estimated bitrate not to change so dramatically.

### What happened?

The estimated bitrate sharply decreased.

### Logs

```
latest: 10000000, loss bitrate: 10000000, delay bitrate: 10000000
delaystats: {13.127066ms 14.36628ms 36.5ms 33ms normal increase 10000000}
latest: 10000000, loss bitrate: 10000000, delay bitrate: 10000000
loss controller increasing; averageLoss: 0, decreaseLoss: 0, increaseLoss: 0
rateController.onReceivedRate: 285030
delaystats: {-13.015515ms -10.3869ms 36.5ms 27ms normal increase 10000000}
latest: 10000000, loss bitrate: 10000000, delay bitrate: 10000000
rateController.onReceivedRate: 221592
delaystats: {532.713µs -9.07026ms 36.5ms 35ms normal increase 10000000}
latest: 10000000, loss bitrate: 10000000, delay bitrate: 10000000
rateController.onReceivedRate: 182895
rateController.onReceivedRate: 194354
rateController.onReceivedRate: 209145
delaystats: {1.158966ms -6.6237ms 36.5ms 51ms normal increase 10000000}
latest: 10000000, loss bitrate: 10000000, delay bitrate: 10000000
loss controller increasing; averageLoss: 0, decreaseLoss: 0, increaseLoss: 0
rateController.onReceivedRate: 177910
rateController.onReceivedRate: 185813
rateController.onReceivedRate: 196080
rateController.onReceivedRate: 203805
delaystats: {43.89668ms 75.56388ms 36.5ms 124ms normal increase 10000000}
latest: 10000000, loss bitrate: 10000000, delay bitrate: 10000000
rateController.onReceivedRate: 129338
rateController.onReceivedRate: 137593
rateController.onReceivedRate: 145966
rateController.onReceivedRate: 154677
delaystats: {-45.174547ms -11.15454ms 36.5ms 110ms normal increase 10000000}
latest: 10000000, loss bitrate: 10000000, delay bitrate: 10000000
rateController.onReceivedRate: 140632
rateController.onReceivedRate: 151864
rateController.onReceivedRate: 166900
delaystats: {15.046823ms 17.29278ms 36.5ms 125ms normal increase 10000000}
latest: 10000000, loss bitrate: 10000000, delay bitrate: 10000000
rateController.onReceivedRate: 175799
rateController.onReceivedRate: 218550
delaystats: {-15.879735ms -12.90072ms 36.5ms 119ms normal increase 10000000}
latest: 10000000, loss bitrate: 10000000, delay bitrate: 10000000
loss controller increasing; averageLoss: 0, decreaseLoss: 0, increaseLoss: 0
rateController.onReceivedRate: 214988
delaystats: {199.162µs -12.12756ms 36.5ms 35ms normal increase 10000000}
latest: 10000000, loss bitrate: 10000000, delay bitrate: 10000000
rateController.onReceivedRate: 208580
delaystats: {6.213µs -11.73912ms 36.5ms 30ms normal increase 10000000}
latest: 10000000, loss bitrate: 10000000, delay bitrate: 10000000
rateController.onReceivedRate: 174357
rateController.onReceivedRate: 187548
rateController.onReceivedRate: 199310
rateController.onReceivedRate: 211071
delaystats: {660.609µs -10.14048ms 36.5ms 36ms normal increase 10000000}
latest: 10000000, loss bitrate: 10000000, delay bitrate: 10000000
loss controller increasing; averageLoss: 0, decreaseLoss: 0, increaseLoss: 0
rateController.onReceivedRate: 189839
rateController.onReceivedRate: 205789
rateController.onReceivedRate: 221738
rateController.onReceivedRate: 240489
rateController.onReceivedRate: 257610
rateController.onReceivedRate: 276259
rateController.onReceivedRate: 293941
delaystats: {27.328607ms 41.21298ms 36.5ms 142ms normal increase 10000000}
latest: 10000000, loss bitrate: 10000000, delay bitrate: 10000000
rateController.onReceivedRate: 266448
rateController.onReceivedRate: 284261
rateController.onReceivedRate: 302073
rateController.onReceivedRate: 319902
rateController.onReceivedRate: 336946
rateController.onReceivedRate: 353991
rateController.onReceivedRate: 371053
rateController.onReceivedRate: 388114
rateController.onReceivedRate: 405289
rateController.onReceivedRate: 422465
rateController.onReceivedRate: 439657
rateController.onReceivedRate: 456848
rateController.onReceivedRate: 468228
rateController.onReceivedRate: 479608
rateController.onReceivedRate: 496359
rateController.onReceivedRate: 513126
rateController.onReceivedRate: 529893
rateController.onReceivedRate: 546661
rateController.onReceivedRate: 563428
loss controller increasing; averageLoss: 0, decreaseLoss: 0, increaseLoss: 0
rateController.onReceivedRate: 510531
rateController.onReceivedRate: 526779
rateController.onReceivedRate: 537485
delaystats: {6.415829ms 51.91056ms 40.5ms 237ms overuse decrease 500000}
latest: 10000000, loss bitrate: 500000, delay bitrate: 500000
```

I added some log statements here and there to get a better picture. Of course I am also happy to provide further information if necessary.

I am not suggesting there's a bug or anything but I'd like to understand a bit better what's going on to potentially mitigate this behaviour if possible.

**Comment by mengelbart** [comment]
The delay-based estimator decreases to `0.85 * lastReceivedRate`, which in this case looks like `0.85 * 537485 = 456862.25`. Do you use a minimum rate of `500000`? The logs look like the estimated bitrate is much higher than the actual rate at which the application outputs media. That should be fine if the actual rate is below the bandwidth limit. But when the rate approaches the link capacity, we want to reduce it to something close to the last known maximum instead of reducing the last estimate, which can be much higher than the link capacity.

I don't know why the received rate estimation only slowly ramps up in your logs even when the initial rate estimation is much higher. Can you confirm the rates coming from the browser are actually that low in the beginning? The delivery rate estimation is currently not very precise, but it should be somewhat close to what is acknowledged by the receiver.

**Comment by streamer45** [comment]
Thanks @mengelbart, that's very insightful. 

This is how I am configuring the estimator at the higher level:

```go
congestionController, err := cc.NewInterceptor(func() (cc.BandwidthEstimator, error) {
    return gcc.NewSendSideBWE(gcc.SendSideBWEInitialBitrate(1_000_000), gcc.SendSideBWEMinBitrate(500_000), gcc.SendSideBWEMaxBitrate(10_000_000))
})
```

The source rate is configured with the following simulcasted tracks:

- 0.5Mb/s (lower quality)
- 1Mb/s (medium quality)
- 2Mb/s (higher quality)

I'd fully expect the incoming stream's bitrate to fluctuate quite a bit given the source of media is screen share and when it goes to static content it's easy to get very low rates. But maybe I am misinterpreting the output of this whole estimation process somehow. As a newcomer to the field, I'd expect to get an approximation on the client's available down-rate, no matter what the current bitrate is, although I understand it's something tricky to guess precisely.

Here's logs from another reproduction attempt (I can provide logs from the beginning if it helps, just let know):

```
delaystats: {343.157µs -1.07712ms 18.5ms 16ms normal increase 10000000}
delaystats: {-283.647µs -1.572ms 18.5ms 95ms normal increase 10000000}
delaystats: {-298.066µs -2.0781ms 18.5ms 19ms normal increase 10000000}
loss controller increasing; averageLoss: 0, decreaseLoss: 0, increaseLoss: 0
rateController.onReceivedRate: 1072762
rateController.onReceivedRate: 1080212
rateController.onReceivedRate: 1103171
rateController.onReceivedRate: 949658
rateController.onReceivedRate: 953296
delaystats: {768.476µs -578.46µs 18.5ms 31ms normal increase 10000000}
rateController.onReceivedRate: 935008
rateController.onReceivedRate: 953840
rateController.onReceivedRate: 939309
rateController.onReceivedRate: 866736
rateController.onReceivedRate: 885682
rateController.onReceivedRate: 882388
rateController.onReceivedRate: 845418
rateController.onReceivedRate: 809747
delaystats: {5.015546ms 8.8062ms 18.5ms 85ms normal increase 10000000}
rateController.onReceivedRate: 828617
rateController.onReceivedRate: 834338
delaystats: {4.889535ms 17.66232ms 18.5ms 10ms normal increase 10000000}
delaystats: {13.557862ms 42.4323ms 18.5ms 33ms normal increase 10000000}
rateController.onReceivedRate: 773424
rateController.onReceivedRate: 757010
rateController.onReceivedRate: 775835
delaystats: {2.613177ms 45.99006ms 18.5ms 13ms overuse decrease 659459}
SendSideBWE.onDelayUpdate: bitrate: 659459, lossStats.TargetBitrate: 659459, delayStats.TargetBitrate: 659459
```

This is from the source (Chrome browser producing the stream):

![image](https://user-images.githubusercontent.com/1832946/186659906-f1addb74-e41f-483a-a4e6-6951b3371ae7.png)

**Comment by mengelbart** [comment]
In this log you can see how the estimator detects overuse and then reduces the estimation to `0.85 * receivedRate`. I assume the beginning of the log shows a ramp up from the initial rate (1_000_000) to the maximum rate (10_000_000)?

> As a newcomer to the field, I'd expect to get an approximation on the client's available down-rate, no matter what the current bitrate is, although I understand it's something tricky to guess precisely.

That is the goal, but when the last estimation is higher than the rate at which data can be sent, we cannot guess the link capacity. The way this estimation works is by trying to increase the sending rate until the interarrival delay between two groups of packets as measured by the receiver increases, which indicates that we are approaching the bandwidth limit. When the application does not produce enough data to probe for higher bandwidths, we will always measure the same interarrival delays and cannot find the bandwidth limit. The actual problem in these logs seems to be that the estimation increases to the maximum, even though the actual delivery rate is application limited at a much lower rate. There are some optimizations possible, but they are currently not implemented in Pion:

- To avoid very high target bitrates which are far from what is delivered, we could detect if the rate is application limited and stop increasing the target rate.
- We could probe for higher rates using padding packets to fill the gap between the rate emitted by the application and the target rate estimation to probe for higher bandwidths.
- There's a somewhat long delay between the time the delay-based estimator first detects a growing interarrival time and the time at which it decreases the rate. We might be able to reduce this in the future but need more tests and experimentation with different parameters first.

**Comment by streamer45** [comment]
> In this log you can see how the estimator detects overuse and then reduces the estimation to 0.85 * receivedRate. I assume the beginning of the log shows a ramp up from the initial rate (1_000_000) to the maximum rate (10_000_000)?

Yep, that's precisely what's happening.

I guess as first step I may try to set the max bitrate to the actual highest value I expect to send from the app level. Although that's not going to protect me from the rate suddenly going down for other reasons (e.g. encoder related).

It sounds like the probing solution you mention may be an interesting option but that raises a few more questions like how frequent should that happen to minimize bandwidth waste or even be detrimental and cause more congestion.

So overall I guess I just hit a potential limitation of the current implementation. Either way, your comments were very informative and helpful, thank you again @mengelbart :raised_hands:

**Comment by mengelbart** [comment]
You're welcome. More optimizations are on the roadmap but will take more time to implement.
I will close the issue but feel free to re-open it if necessary.
