### ISSUE TITLE
Logic when generating TWCC feedback packets seems strange

### ISSUE THREAD

**Issue by k0nserv** [pion/interceptor#159]
The logic when generating feedback packets for TWCC seems a bit odd, specifically when there are few received packets  https://github.com/pion/interceptor/blob/a82b843030a8e8a046cbda37ce33a100ddb3b5f1/pkg/twcc/twcc.go#L75-L78

In webrtc-rs/webrtc we've seen this logic cause the generated packets to have no chunks which in turn causes libWebRTC to ignore them with a message like:

```
[64267:81923:1013/111056.055484:WARNING:transport_feedback.cc(420)] Buffer too small (16 bytes) to fit a FeedbackPacket. Minimum size = 18
```

It would seem that no packet should be generated in the event that `len(r.receivePackets) < 2` and the `r.receivedPackets` shouldn't be cleared

**Comment by k0nserv** [comment]
cc @mengelbart

**Comment by Sean-Der** [comment]
thank you so much for reporting this @k0nserv 

Got so caught up in other things completely missed this one :(
