### ISSUE TITLE
Bandwidth Estimation

### ISSUE THREAD

**Issue by Sean-Der** [pion/interceptor#16]
Downstream projects implement this today. Would be really great to bring them into this project! What we need

## Message Generation (available in Ion today)
* Sender and Receiver Reports
* Transport Wide Congestion Control

## Processing of those reports (Not available in Go yet)
* [draft-alvestrand-rmcat-congestion](https://tools.ietf.org/html/draft-ietf-rmcat-gcc-02)

**Comment by Sean-Der** [comment]
@OrlandoCo @adwpc @tarrencev Would love your opinion on this!

How realistic would it be to upstream this stuff from ion? I am happy to do the work. Conceptually is it to possible to express this stuff as interceptors? Any pitfalls do I need to be worried about besides performance?

**Comment by OrlandoCo** [comment]
@Sean-Der ion-sfu buffer moved to interceptors api, and provides: RR,REMB,TWCC,NACK and packet buffer:

https://github.com/pion/ion-sfu/tree/master/pkg/buffer

ATM is not configurable and not fully documented, but hopefully we can do it soon.

**Comment by Sean-Der** [comment]
Covered by README.md
