### ISSUE TITLE
What's the unit of ReceivedRTPStreamStats's Jitter?

### ISSUE THREAD

**Issue by asticode** [pion/interceptor#161]
Hey,

First off a big bravo for the stat's interceptor, it's really awesome! ❤️ 

However I'm wondering what's the unit of ReceivedRTPStreamStats's Jitter? 🤔 If it's not a `time.Duration`, does it make sense to convert to it? If so, how can I do it?

Cheers
Quentin

**Comment by adriancable** [comment]
It's in units of the stream's clock rate. So for example (for a video stream) 90000 is a jitter of 1 second.

**Comment by asticode** [comment]
Thanks a lot! ❤️

**Comment by ghettovoice** [comment]
@adriancable I'm not sure, probably there is a jitter setup inconsistency between `InboundRTPStreamStats` and  `RemoteInboundRTPStreamStats`. 
If I'm not wrong, `InboundRTPStreamStats.Jitter` is in clock rate units like you wrote (https://github.com/pion/interceptor/blob/master/pkg/stats/stats_recorder.go#L146C15-L146C117), but `RemoteInboundRTPStreamStats.Jitter` is in seconds (https://github.com/pion/interceptor/blob/master/pkg/stats/stats_recorder.go#L227C15-L227C49).
