### ISSUE TITLE
Interceptors not useful by default/Require user to call ReadRTCP

### ISSUE THREAD

**Issue by Sean-Der** [pion/interceptor#20]
If users want NACKs they need to call `ReadRTCP`, otherwise the func returned by `BindRTCPReader` isn't executed. For new users I worry this will be easy to accidental not do. Do others think this will be an issue?

* Can we notify the users that certain features aren't available unless they call `Read` or `ReadRTCP` ?
* Should we revisit the design?

For now I am updating my `pion/webrtc` PR to add `Read` calls.

**Comment by masterada** [comment]
What do you think about reading and droppnig rtcp packets before the first call to ReadRTCP?

**Comment by OrlandoCo** [comment]
This is a hard one, for me Is better to call rtcp/rtp read methods, so I can have more control on interceptors, and get the interceptor parameters. Calling the reader without doing explicitly can be tricky and prone to bugs

**Comment by Sean-Der** [comment]
I think things are great as is. If a user opens an issue it is worth further exploration though.

It might be nice to provide a helper function to drive things. `ReadForever` and would read until it got an error. That way users don't need to spawn a goroutine themselves if they don't care about the results.
