### ISSUE TITLE
GCC: differences between different GCC implementation

### ISSUE THREAD

**Issue by sterlingdeng** [pion/interceptor#283]
### Your environment.
  - Version: Master

### What did you do?

I have an open issue on a gstreamer GCC implementation that discusses the issue. 
https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/issues/607

### What did you expect?

Libwebrtc and pion GCC implementation should be the same.

### What happened?

Differences in the formula to calculate average loss

**Comment by sterlingdeng** [comment]
I think the author of the GCC implementation is @mengelbart, could you help take a look at this?

**Comment by boks1971** [comment]
Expanding and re-arranging the terms give the same formula.

**Comment by sterlingdeng** [comment]
Thanks for pointing out that out.. it's obvious after I set both formulas equal to one another
