### ISSUE TITLE
Next Steps

### ISSUE THREAD

**Issue by Sean-Der** [pion/interceptor#3]
@masterada @at-wat Just starting a tracking issue, feel free to add anything to this list you think are important! I will also be helping after `v3.0.0` is tagged :)

* [x] Create examples
* [x] Move NACK to dedicated pkg. Should top-level just be structure, and each specific topic be their own folder?
* [x] Tests
* [x] Finish README
  - [x] Elevator Pitch
  - [x] Roadmap/Interceptor Types
  - [x] Motivations for Interceptors/why we did it this way
  - [x] Architecture/Design Document (in own .md file?)

**Comment by Sean-Der** [comment]
@aler9 also would love your opinion :)

**Comment by masterada** [comment]
Do we need WASM build in this project? If not, I think we should remove WASM test.

**Comment by Sean-Der** [comment]
@masterada I think WASM tests might actually work with no modifications!

`pion/webrtc` isn't very WASM friendly. However `pion/rtp` and `pion/rtcp` should be just fine. I think it is worth having it work. In the future WASM support could unlock some really interesting stuff.

If we can get socket support in the browser we could run Pion in the browser right away! I don't have any concrete plans, but I think it could be something that will suprise us eventually :)

**Comment by Sean-Der** [comment]
What do you think of moving the tests from `pion/webrtc` into here for interceptors? Just trying to find a good mix between bringing the time down to run all the tests without lowering the software quality :)

For me `pion/webrtc` sits at ~90 seconds, which isn't terrible but we can always do better :)

**Comment by masterada** [comment]
> What happens if you just remove all exclusions?
Yes, they run, just seemed a bit unnecessary to run tests twice, but doesn't really hurt I guess.

> What do you think of moving the tests from pion/webrtc into here for interceptors?
The test in interceptor_test is there to make sure interceptors are properly called everywhere (so it's more of a test for the intergration of interceptors into webrtc), so I think we should leave it there. Tests for specific interceptors can go into this packet (eg: see my nack pr)
