### ISSUE TITLE
TWCC isn't performing as well as Browser <-> Browser

### ISSUE THREAD

**Issue by Sean-Der** [pion/interceptor#61]
When using `save-to-disk` I am not seeing the BWE ramping up as fast as expected. 

When doing browser <-> browser I see a ramp up like this
<img width="954" alt="Screen Shot 2021-09-08 at 2 29 03 PM" src="https://user-images.githubusercontent.com/1302304/132565048-6fed6f39-6de0-425f-9310-ab88d40f59f8.png">

When doing browser <-> pion I see this
<img width="951" alt="Screen Shot 2021-09-08 at 2 28 29 PM" src="https://user-images.githubusercontent.com/1302304/132565106-58d317b3-b5aa-4267-b497-c872040dacfc.png">

**Comment by Sean-Der** [comment]
I am looking into this now! I will make minor changes as I go, it is a good chance for me to really learn the code as well :)

**Comment by mengelbart** [comment]
I just looked into it but I am not yet sure what is causing this. I can see that Chrome is decoding more run length chunks than the interceptor is sending, but I am not sure yet why this is happening and if it is related. I will continue with this tomorrow, maybe some more debug output from Chrome will be helpful to see what's going on.

**Comment by Sean-Der** [comment]
@mengelbart i got this one! I want to learn the code myself. If you wanna get the NetworkConditoner I think that is more deep work 

throw bug fixing my way :)
