### ISSUE TITLE
when will google congestion control be released?

### ISSUE THREAD

**Issue by xingzhao-tt** [pion/interceptor#62]
## Summary

I am hungry for Google Congestion Control

## Motivation

Why are we doing this? What use cases does it support? What is the expected outcome? Is this available in other implementations? Can this not be implemented using primitives?

## Describe alternatives you've considered

A clear and concise description of the alternative solutions you've considered.

**Comment by Sean-Der** [comment]
Hey @xingzhao-tt 

I expect we will have a rough implementation in ~2 months. @mengelbart is actively working on this, and is being tracked in https://github.com/pion/interceptor/issues/25

**Comment by xingzhao-tt** [comment]
Hey @Sean-Der @mengelbart 

Got it. Really appreciate your contributions, this project saves us lots of time.
